version: '3.8'

services:
  app:
    container_name: nest-api-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.staging
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    restart: unless-stopped
