version: '3.8'

services:
  app:
    container_name: nest-api-boilerplate-stg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    restart: unless-stopped
