version: '3.9'

services:
  app:
    image: node:21
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    env_file:
      - .env
    command: bash -c "yarn && yarn prisma generate && yarn start:dev"
    ports:
      - 3000:3000
