version: '3.8'

services:
  app:
    container_name: nest-api-boilerplate-stg
    build:
      context: .
      dockerfile: Dockerfile.staging
    env_file: .env.staging
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    restart: unless-stopped
    networks:
      - mysql

networks:
  mysql:
    external: true
